#!/bin/bash

# BEGIN INIT INFO
# Provides:          artillery
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Artillery - Advanced threat intelligence
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
# END INIT INFO
# artillery
# description: Artillery - ATIF
# processname: artillery

DAEMON_PATH = "/var/artillery"

DAEMON = /var / artillery / artillery.py
DAEMONOPTS = ""

NAME = artillery
DESC = "Artillery - Advanced threat intelligence"
PIDFILE = /var / run / artillery.pid
SCRIPTNAME = /etc / init.d / artillery

case "$1" in
start)
    printf "%-50s" "Starting Artillery..."
    cd $DAEMON_PATH
    PID=`$DAEMON $DAEMONOPTS > /dev / null 2 > &1 & echo $!`
    # echo "Saving PID" $PID " to " $PIDFILE
        if [-z $PID]; then
            printf "%s\n" "Fail"
        else
            echo $PID > $PIDFILE
            printf "%s\n" "Ok"
        fi;;
status)
        printf "%-50s" "Checking Artillery..."
        if [-f $PIDFILE]; then
            PID=`cat $PIDFILE`
            if [-z "`ps axf | grep ${PID} | grep -v grep`"]; then
                printf "%s\n" "Process dead but pidfile exists"
            else
                echo "Running"
            fi
        else
            printf "%s\n" "Service not running"
        fi;;
stop)
        printf "%-50s" "Stopping Artillery..."
            PID=`cat $PIDFILE`
            cd $DAEMON_PATH
        if [-f $PIDFILE]; then
            kill - HUP $PID
            printf "%s\n" "Ok"
            rm - f $PIDFILE
        else
            printf "%s\n" "pidfile not found"
        fi;;

restart)
    $0 stop
    $0 start;;

*)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac
